services:
  postgres:
    image: postgres:14.11
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres
      POSTGRES_DB: medical
    container_name: postgres